name: hart
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49403
title: hart roberts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00b5e4'
    - '#ffffff'
    - '#c6e3ff'
    - '#80ffff'
    - '#00ffff'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
