name: hart
favicon: null
layout_spectrum: 1
typography_spectrum: 0.07565
title: Digital + Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a4a4a4'
    - '#dddddd'
    - '#6e6e6e'
    - '#4b4b4b'
    - '#090909'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
